### ISSUE TITLE
Settlement tile is not guaranteed to be claimed by settlement owner

### ISSUE THREAD

**Issue by Toby222** [Danimineiro/Empire-Rewritten#32]
For one reason or another, Settlements' tiles can be claimed by other factions
![image](https://user-images.githubusercontent.com/14962962/167430556-226f4977-36b0-4978-8881-db508aed3ba3.png)

**Comment by jliu7350** [comment]
In case this hasn't been addressed yet, this is because settlements currently claim at a time, which means that whichever settlement goes first gets all the tiles (in this case, purple). The question then is if two settlements have a claim on the same tile, which one gets it? Potentially it's the closer one, but what if their levels (and thus claim radius) are different?

**Comment by MajikalExplosions** [comment]
In case this hasn't been addressed yet, this is because settlements currently claim at a time, which means that whichever settlement goes first gets all the tiles (in this case, purple). The question then is if two settlements have a claim on the same tile, which one gets it? Potentially it's the closer one, but what if their levels (and thus claim radius) are different?

**Comment by RecompiledBirds** [comment]
Something else that could be done, as this issue with with the starting settlements, might be ensuring that a settlement can *only* be spawned in unclaimed tiles?

**Comment by Toby222** [comment]
Claiming happens after spawning, so that'd require changing that around
